[build.env]
passthrough = [
    "CMAKE_PREFIX_PATH",
]

[target.x86_64-unknown-linux-gnu]
pre-build = [
    "apt-get update && apt-get install -y wget",
    "wget -q https://github.com/Kitware/CMake/releases/download/v3.20.6/cmake-3.20.6-Linux-x86_64.sh -O /tmp/cmake.sh && sh /tmp/cmake.sh --skip-license --prefix=/usr/local && rm /tmp/cmake.sh",
    "apt-get install -y libusb-1.0-0-dev libudev-dev pkg-config && rm -rf /var/lib/apt/lists/*"
]